# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('publication_date', models.DateField()),
                ('title', models.CharField(max_length=255, unique=True)),
                ('teaser', models.TextField()),
                ('embed_url', models.URLField(max_length=255)),
                ('download_url', models.URLField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['publication_date'],
            },
        ),
    ]
