# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='listened',
            field=models.BooleanField(default=False),
        ),
    ]
